"""sync_all_models

Revision ID: 8ba10766ed26
Revises:
Create Date: 2026-03-11 00:37:28.943067
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ba10766ed26"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clone_blueprints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("blueprint_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("manufacture_time_sec", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blueprint_id"),
    )
    op.create_table(
        "killmails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kill_id", sa.Integer(), nullable=False),
        sa.Column("victim_address", sa.String(length=66), nullable=False),
        sa.Column("victim_name", sa.String(length=255), nullable=True),
        sa.Column("victim_corp_id", sa.Integer(), nullable=True),
        sa.Column("victim_corp_name", sa.String(length=255), nullable=True),
        sa.Column("killer_address", sa.String(length=66), nullable=False),
        sa.Column("killer_name", sa.String(length=255), nullable=True),
        sa.Column("killer_corp_id", sa.Integer(), nullable=True),
        sa.Column("killer_corp_name", sa.String(length=255), nullable=True),
        sa.Column("solar_system_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kill_id"),
    )
    op.create_table(
        "orbital_zones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("coordinates_hash", sa.String(length=255), nullable=True),
        sa.Column("feral_ai_tier", sa.Integer(), nullable=False),
        sa.Column("last_scanned", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("zone_id"),
    )
    op.create_table(
        "feral_ai_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("previous_tier", sa.Integer(), nullable=True),
        sa.Column("new_tier", sa.Integer(), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["orbital_zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_intel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("threat_signature", sa.String(length=255), nullable=True),
        sa.Column("anomaly_type", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["orbital_zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tribe_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("discord_webhook_url", sa.String(length=500), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("last_triggered", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tribe_id"],
            ["tribes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clone_id", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("blueprint_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("manufactured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location_zone_id", sa.Uuid(), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_zone_id"],
            ["orbital_zones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clone_id"),
    )
    op.create_table(
        "crowns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crown_id", sa.String(length=100), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("crown_type", sa.String(length=100), nullable=False),
        sa.Column("attributes", sa.Text(), nullable=True),
        sa.Column("equipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chain_tx_id", sa.String(length=100), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crown_id"),
    )
    op.create_table(
        "ledger_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tribe_id", sa.Uuid(), nullable=False),
        sa.Column("tx_digest", sa.String(length=100), nullable=False),
        sa.Column("from_address", sa.String(length=66), nullable=False),
        sa.Column("to_address", sa.String(length=66), nullable=False),
        sa.Column("amount", sa.String(length=78), nullable=False),
        sa.Column("coin_type", sa.String(length=255), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tribe_id"],
            ["tribes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tx_digest"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("scanner_id", sa.Uuid(), nullable=True),
        sa.Column("result_type", sa.String(length=50), nullable=False),
        sa.Column("signature_type", sa.String(length=50), nullable=True),
        sa.Column("resolution", sa.Integer(), nullable=False),
        sa.Column("result_data", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(length=100), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scanner_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["orbital_zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "members", sa.Column("ship_class", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "ship_class")
    op.drop_table("scans")
    op.drop_table("ledger_transactions")
    op.drop_table("crowns")
    op.drop_table("clones")
    op.drop_table("alert_configs")
    op.drop_table("scan_intel")
    op.drop_table("feral_ai_events")
    op.drop_table("orbital_zones")
    op.drop_table("killmails")
    op.drop_table("clone_blueprints")
    # ### end Alembic commands ###
